data:
  env: product-service-prod666nima
  password: '{cipher}AQAOmxlkToCjNKyAsPZB9qzUERhwYqUqMJiVO8ztOYnaIEYxdheCN0ygqmZTjGD3FW+PZT54xplwzhbrsvE8BKAxAT4rdohZu7KE3j1BKiD1wBV44VTITBh5eu0VA1vtmz/KRXNx1o3NTcS9sNBxaWe2OliYtSlDZvBuzTl5NyGrlSpjY8aistk4AN8B2hMNo+rUrT2tzC989s1urvox+d/IPCngYwni2tciU/PkeVOp5D3Z8brw6wJX9C6YFMSIYaeieMYMkF+OFSWvaqFqfz6qFDUPdh6cmlOQm02jtESkrI56GcndlbeBU7um2SIVoxoNCBN8kK7iWci6o4S1Z9355vju2aCheAa6haRtAUVtYtgF33MSdCKGtRoaNIUqh8w='
